name: Publish release to NPM
run-name: Publish - ${{ github.ref }}

on:
  release:
    types: [published]

permissions:
  id-token: write # GitHub OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          scope: "@videodock"
      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
      # Ensure npm 11.5.1 or later is installed for publishing with trusted publisher (OIDC)
      - name: Update npm
        run: pnpm install -g npm@latest
      - name: Install dependencies
        run: pnpm install
      - name: Publish to NPM
        run: npm publish --access public
